source 'https://rubygems.org'
gem 'github-pages'
gem 'therubyracer'
gem 'jekyll-redirect-from'
gem 'bootstrap-sass'
gem 'jekyll-bootstrap-sass'
gem 'octopress-paginate', git: 'https://github.com/concur/paginate.git', branch: 'deprecation-warning-fix'
